# Generated by Django 3.0.6 on 2020-05-30 22:36

from django.db import migrations, models

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacuna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('doctor', models.CharField(max_length=100)),
                ('especie', models.CharField(max_length=30)),
                ('raza', models.CharField(blank=True, max_length=30)),
                ('descripcion', models.TextField()),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Macho'), ('H', 'Hembra')], max_length=1)),
                ('fecha', models.DateTimeField()),
                ('edad', models.IntegerField(null=True)),
                ('vacunas', models.ManyToManyField(blank=True, to='mascotas.Vacuna')),
            ],
        ),
    ]
